version: "3.9"

services:
  dind:
    image: docker:24-dind
    privileged: true
    command: ["--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2"]
    environment:
      - DOCKER_TLS_CERTDIR=
    networks: [jenkins]
    volumes:
      - docker_cache:/var/lib/docker

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    depends_on: [dind]
    networks: [jenkins]
    volumes:
      - jenkins_home:/var/jenkins_home

networks:
  jenkins:

volumes:
  jenkins_home:
  docker_cache:
