version: "3.9"

services:
  dind:
    image: docker:24-dind
    container_name: dind 
    privileged: true
    command: ["--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2"]
    environment:
      - DOCKER_TLS_CERTDIR=
    networks: [jenkins]
    volumes:
      - docker_cache:/var/lib/docker
      - jenkins_home:/var/jenkins_home

    healthcheck:
      test: ["CMD-SHELL", "apk add --no-cache curl >/dev/null 2>&1 && curl -fs http://localhost:2375/_ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    depends_on:
      dind:
        condition: service_healthy
    networks: [jenkins]
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker:ro     
    restart: unless-stopped

networks:
  jenkins:

volumes:
  jenkins_home:
  docker_cache:
